### ISSUE TITLE
load locations and flows from REST

### ISSUE THREAD

**Issue by kaxap** [ilyabo/flowmap.blue#18]
Hi,

Is it possible to load the data from a REST endpoint instead of GS?
If not, could you please briefly outline what parts of code to modify?

**Comment by ilyabo** [comment]
Not it's not supported ATM. 

Take a look at [GSheetsFlowMap](https://github.com/ilyabo/flowmap.blue/blob/master/src/GSheetsFlowMap.tsx). You can create an alternative component e.g. `RestApiFlowMap` and replace the sheetFetchers with `connect()` HOC from [react-refetch](https://github.com/heroku/react-refetch) to get the data from a REST API.

**Comment by kaxap** [comment]
looks spooky (I am a backend engineer). Any chance for the REST implementation in near future?
Also, is there any way to donate?

**Comment by ilyabo** [comment]
I will think about it and let you know

**Comment by kaxap** [comment]
Any news on this?

**Comment by ilyabo** [comment]
Not yet, but I will try to come up with a quick solution later this week. Will let you know.

**Comment by ilyabo** [comment]
You can now pass as query params the URLs to fetch the locations and the flows from as CSV files. 

I created [this public gist](https://gist.github.com/ilyabo/a7b9701424257146b571149d92a14926/) to serve the files from. 

Now I can load them into a flow map like this:
http://flowmap.blue/from-url?flows=https://gist.githubusercontent.com/ilyabo/a7b9701424257146b571149d92a14926/raw/2e9e1e9bcf64cf0090781b451037229ccb78e1b1/flows.csv&locations=https://gist.githubusercontent.com/ilyabo/a7b9701424257146b571149d92a14926/raw/2e9e1e9bcf64cf0090781b451037229ccb78e1b1/locations.csv

Note that the server you are fetching from needs to have [CORS enabled](https://enable-cors.org/).

**Comment by kaxap** [comment]
Greatly appreciated!
