### ISSUE TITLE
How to adjust the timeline's interval

### ISSUE THREAD

**Issue by TzanC** [ilyabo/flowmap.blue#21]
Hi, Mr.Ilya Boyandin
     I wonder how to adjust the swiper's interval in timeline. The outcome of the timeline that I wish my flow map to be would be like the timeline in [Hourly NYC Uber trips](https://flowmap.blue/1LoeL7i9GHl67Y4SPyp5fiyex6lRqxOuib_mfmg978q4) flow map ,but I can't find any clue from its spreadsheet.

**Comment by ilyabo** [comment]
The interval is determined by the date precision which the app tries to determine by trying to round the dates specified to the different intervals and using the finest granularity found.
So if your dates are like `2005-01` it will be months, if they are like `2005-01-01 12:00` it will be hours, if they are like `2005-01-01 12:01` then minutes. So to adjust the interval you need to round your dates to that interval.

**Comment by TzanC** [comment]
Thanks for answering me the question. Here is my flow map: [Average Passenger flow by hour of Taipei Metro during 2019](https://flowmap.blue/1GZzLusglIjIr5OlgbKzeFpRIVxidOnPnylvj0H-G5Cg). Since the timeline's interval is cut into hours, I want to let the users of this map know what has happened during each hours, instead of letting them drag the swiper's interval by themselves. But, in the flow map which I've made, the timeline's swiper span the whole day, which is different form the [Hourly NYC Uber trips](https://flowmap.blue/1LoeL7i9GHl67Y4SPyp5fiyex6lRqxOuib_mfmg978q4) flow map. How can I adjust the swiper's interval?

**Comment by ilyabo** [comment]
Ah, I see now what you mean. You can adjust it yourself and then use the link for embedding with the "Current view of the map". Here there is the parameter `t` specifying the time interval.

https://flowmap.blue/1GZzLusglIjIr5OlgbKzeFpRIVxidOnPnylvj0H-G5Cg/embed?v=25.061209,121.517473,11.44,0,0&a=0&b=1&bo=75&c=0&d=1&lt=1&lfm=ALL&t=20190101T000000,20190101T010000&col=Default&f=50

**Comment by ilyabo** [comment]
BTW, can I add your map to the list of examples on the website?

**Comment by TzanC** [comment]
Thank you for your helpful reply. Of course you can add my map to your website.

**Comment by TzanC** [comment]
This is the latest version of my flow map: [Commuters of Taipei Metro in 2019](https://flowmap.blue/1snSJx8zPZQStNEmN0qN10VRpf3acjRRJHLxH1yUCPws?v=25.063043,121.514689,10.71,0,0&a=0&b=1&bo=75&c=1&d=1&lt=1&lfm=ALL&t=20190101T080000,20190101T090000&col=Default&f=50).
