### ISSUE TITLE
Independent deckgl layer?

### ISSUE THREAD

**Issue by layik** [ilyabo/flowmap.blue#22]
Hi there, just came across the amazing flowmapping tool. I will experiment with some huge dataset I have access to, but would be great to integrate it into our [eAtlas](https://github.com/layik/eAtlas). Is there any plans to release a DeckGL layer? Or all this amazing aggregation is not possible within one?

Apologies if considered question and close as you see it fit. Thanks

**Comment by layik** [comment]
Arge! Ignore me :)

**Comment by ilyabo** [comment]
If you mean a pure JS Deck.gl layer, check this out https://github.com/ilyabo/flowmap.gl-purejs-example/
